### ISSUE TITLE
Spinner instead of calculation results on Kubuntu 20.04 in plasma-applet-qalculate

### ISSUE THREAD

**Issue by MurzNN** [dschopf/qalculate#35]
plasma-applet-qalculate widget installs and shows successfully on Kubuntu 20.04 from https://launchpad.net/~dschopf/+archive/ubuntu/plasma-applet-qalculate/+packages 

But when I executing calculation - I see infinite spinner instead of result. Here is output of `plasmoidviewer` - when spinner shows I see no error output:
```
$ plasmoidviewer -a org.kde.plasma.qalculate
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
org.kde.plasmaquick: Applet preload policy set to 1
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:76:9: Unable to assign [undefined] to QStringList
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:75:9: Unable to assign [undefined] to int
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:75:9: Unable to assign [undefined] to int
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:76:9: Unable to assign [undefined] to QStringList
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x55d25764dbd0)
trying to show an empty dialog
trying to show an empty dialog
```

![image](https://user-images.githubusercontent.com/336662/83678401-5e37d580-a5e6-11ea-89fd-4bee6c9ca5bc.png)

Packages `qalc` and `qalculate-gtk` installs and shows well.

Can you please help debug this issue?

**Comment by dschopf** [comment]
Fixed in master. It will take some time to update the PPA.

**Comment by MurzNN** [comment]
Unfortunately, it Failed to build, here is build log https://launchpad.net/~plasma-applet-qalculate/+archive/ubuntu/daily/+recipebuild/2581341 - can you fix this?
```
subprocess.CalledProcessError: Command '['quilt', 'push', '-a', '-v']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/git-build-recipe", line 9, in <module>
    load_entry_point('git-build-recipe==0.1', 'console_scripts', 'git-build-recipe')()
  File "/usr/lib/python3/dist-packages/gitbuildrecipe/main.py", line 172, in main
    force_native_format(working_directory, current_format)
  File "/usr/lib/python3/dist-packages/gitbuildrecipe/deb_util.py", line 236, in force_native_format
    convert_3_0_quilt_to_native(working_tree_path)
  File "/usr/lib/python3/dist-packages/gitbuildrecipe/deb_util.py", line 223, in convert_3_0_quilt_to_native
    raise Exception("Failed to apply quilt patches")
Exception: Failed to apply quilt patches
```

**Comment by dschopf** [comment]
There are some patches which no longer apply properly because I added them to my repo. Unfortunately I don't know how to fix that. My PPA should now have the updated packages which work again with Ubuntu.

**Comment by MurzNN** [comment]
Thanks, with your ppa all fixed with last release!
